// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RzluzPqwtsMfXJkxRdO7LEwDA0TVWCo',
    appId: '1:578123178626:web:c66a7b900cda36f2304a9b',
    messagingSenderId: '578123178626',
    projectId: 'ng-town-car-ride',
    authDomain: 'ng-town-car-ride.firebaseapp.com',
    storageBucket: 'ng-town-car-ride.firebasestorage.app',
    measurementId: 'G-864N8EXW64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACl0SiAUyyn6IHbidq1LgWWuPbsMnvkKA',
    appId: '1:578123178626:android:39450d33c110180c304a9b',
    messagingSenderId: '578123178626',
    projectId: 'ng-town-car-ride',
    storageBucket: 'ng-town-car-ride.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw36QcNeXi8NUg66NK8UGLyuB2KbH7Ku4',
    appId: '1:578123178626:ios:4409e867b75ab708304a9b',
    messagingSenderId: '578123178626',
    projectId: 'ng-town-car-ride',
    storageBucket: 'ng-town-car-ride.firebasestorage.app',
    iosBundleId: 'ngtownride.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw36QcNeXi8NUg66NK8UGLyuB2KbH7Ku4',
    appId: '1:578123178626:ios:bb280ca7f62704a0304a9b',
    messagingSenderId: '578123178626',
    projectId: 'ng-town-car-ride',
    storageBucket: 'ng-town-car-ride.firebasestorage.app',
    iosBundleId: 'ngtownride.driver',
  );
}
